pipeline {
    agent any

    tools {
        maven 'Maven'
    }
    
    environment {
        DOCKER_IMAGE = 'fquisiguina/tallergeneral' // Reemplaza con tu usuario e imagen
        DOCKER_CREDENTIALS = 'dockerhub' // ID de las credenciales en Jenkins
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm // Clona el repositorio
            }
        }

        stage('Build Maven') {
            steps {
                script {
                    dir('first-api-rest') { // Cambia "first-api-rest" a la carpeta donde está el POM
                        sh 'mvn clean install'
                    }
                }
            }
        }

        stage('Verify Docker') {
            steps {
                sh 'docker --version'
            }
        }
        
        stage('Build Docker Image') {
            steps {
                script {
                    sh 'docker build -t $DOCKER_IMAGE:latest .'
                }
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(credentialsId: env.DOCKER_CREDENTIALS, usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh """
                        echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
                        docker push $DOCKER_IMAGE:latest
                    """
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Check the logs.'
        }
    }
}
